version: '3.9'
services:
  mysql-contenedor:
    image: mysql:5.7
#    container_name: mysql-contenedor
    restart: always
    environment:
       MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: 29031999
#      MYSQL_DATABASE: 'netflix-dev-mysql'
#      MYSQL_USER: 'usr-netflix-mysql'
#      MYSQL_PASSWORD: 'pwd-netflix-mysql'
#      MYSQL_ROOT_PASSWORD: 'pwd-netflix-mysql'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
#    expose:
#      - '3306'
    healthcheck:
      test: [ "CMD", "usr-netflix-mysql", "ping", "-ppwd-netflix-mysql", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 10
  mongocontenedor:
    image: mongo
#    container_name: mongo-contenedor
    restart: always
    environment:
#      MONGO_INITDB_DATABASE: 'netflixdevmongo'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
#    expose:
#      - 27017
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  zipkin-contenedor:
    image: openzipkin/zipkin-slim
#    container_name: zipkin-contenedor
#    environment:
#      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
#    expose:
#      - 9411
#    depends_on:
#      - storage-contenedor
#  storage-contenedor:
#    image: busybox:1.31.0
#    container_name: storage-contenedor
  rabbitmq-contenedor:
    image: rabbitmq:3-management
#    container_name: rabbitmq-contenedor
#    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
#    expose:
#      - 15672
#      - 5672