server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-catalog

  data:
    mongodb:
      username: root
      password: root
      database: catalog
      port: 27017
      host: localhost
      authentication-database: admin

#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/movie
#    username: root
#    password: 123456 #29031999

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  zipkin:
     baseUrl: http://localhost:9411/

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
        defaultZone: http://localhost:8761/eureka

resilience4j.retry:
  instances:
    retryMusic:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException

resilience4j.circuitbreaker:
  instances:
    clientMusic:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10