server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  application:
    name: api-movie

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netflix
    username: root
    password: 29031999

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  zipkin:
    baseUrl: http://localhost:9411/

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka